name: Go

on:
  push:
    branches: [ v1.0 ]
  pull_request:
    branches: [ v1.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Gen Doc
        run: go generate
        if: github.event == 'push'

      - name: Commit Doc
        uses: EndBug/add-and-commit@v7.2.1
        with:
          message: update docs

      - name: Build
        run: go build -v ./...
